api/urls.py
from django.conf.urls import url, include
from django.views.generic import TemplateView


urlpatterns = [
    url(r'^result/', include('result.api.urls', namespace='result_api')),
]

befaq/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.views import login, logout
from django.views.generic import RedirectView

urlpatterns = [
    url(r'^login/$', login, {'template_name': 'login.html'}, name='login'),
    url(r'^logout/$', logout, {'next_page': '/'}, name='logout'),
    url(r'^admin/', admin.site.urls),

    url(r'^api/', include('api.urls')),
    url(r'^result/', include('result.urls')),
    url(r'^madrasa/', include('madrasa.urls')),
    url(r'^student/', include('student.urls')),

    url(r'^$', RedirectView.as_view(url='/result', permanent=False))
]

madrasa/urls.py
from django.conf.urls import url

from .views import (MadrasaCreate,
                    MadrasaDetail,
                    MadrasaUpdate,
                    MadrasaList, )

app_name = 'madrasa'

urlpatterns = [
    url(r'add', MadrasaCreate.as_view(), name='madrasa_add'),
    url(r'update/(?P<pk>\d+)/', MadrasaUpdate.as_view(), name='madrasa_update'),
    url(r'list', MadrasaList.as_view(), name='madrasa_list'),
    url(r'(?P<pk>\d+)/', MadrasaDetail.as_view(), name='madrasa_detail'),
]

result/urls.py
from django.conf.urls import url

from result.views import (result_search,
                          result_detail,
                          top_results,
                          add_result,
                          select_student_to_add_result,
                          )


app_name = 'result'

urlpatterns = [
    url(r'^top/$', top_results, name='top_results'),

    url(r'^add/$', select_student_to_add_result, name='select_student_to_add_result'),
    url(r'^add/(?P<id>\d+)/$', add_result, name='add_result'),

    url(r'^(?P<id>\d+)/$', result_detail, name='result_detail'),
    url(r'^$', result_search, name='result_search'),
]

student/urls.py
from django.conf.urls import url

from .views import (StudentCreate,
                    StudentDetail,
                    StudentUpdate,
                    StudentList,
                    StudentWithoutResultList,)

app_name = 'student'

urlpatterns = [
    url(r'^add$', StudentCreate.as_view(), name='student_add'),
    url(r'^update/(?P<pk>\d+)/$', StudentUpdate.as_view(), name='student_update'),
    url(r'^list$', StudentList.as_view(), name='student_list'),
    url(r'^without_result$', StudentWithoutResultList.as_view(), name='student_without_result'),
    url(r'^(?P<pk>\d+)/$', StudentDetail.as_view(), name='student_detail'),
]

student/models.py
from django.core.urlresolvers import reverse
from django.db import models
from django.db.models import Max

from madrasa.models import Madrasa

REGISTRATION_YEARS = (
    ('2016', '2016'),
    ('2017', '2017'),
    ('2018', '2018'),
)

MARHALA = [
    ('takmil', 'Takmil'),
    ('fazilat', 'Fazilat'),
    ('sanabia', 'Sanabia Ulia'),
    ('mutawassitah', 'Mutawassitah'),
    ('ibtedaiyah', 'Ibtedaiyah'),
    ('hifz', 'Hifzul Quran'),
    ('tazbid', 'Ilmut Tazbid wal Qirat'),
]

SUBJECT_LIST = {
    'takmil':['bukhari 1','bukhari 2','muslim 1','muslim 2','tirmizi 1','tirmizi 2','abu daud','nasai & ibne majah','tahabi','muattan'],
    'fazilat':['meshkat 1','meshkat 2','bayjabi','hedaya 3','hedaya 4','sharhul akaid','nukhbah','tahrik'],
    'sanabia':['mukhtasar','nurul anwar','makamat','tarzama','sharhe bekaya','siraji','insha'],
    'mutawassitah':['nahbemir','panjeganj','rawja','sharhe miat','malabudda','seerat','bangla 7'],
    'ibtedaiyah':['najira','urduki tesri','bangla 5','gonit','talimul islam 4','farsi','somaj biggan'],
    'hifz':['hifz','tajbid','diniyat'],
    'tazbid':['hadar','hifj','tajbid','tartil'],
}


class StudentManager(models.Manager):
    def with_result(self):
        students_with_result = self.filter(result__isnull=False)
        return students_with_result

    def without_result(self):
        students_with_result = self.filter(result__isnull=True)
        return students_with_result


class Student(models.Model):
    name          = models.CharField(max_length=100)
    father        = models.CharField(max_length=100)
    address       = models.CharField(max_length=255,
                                     null=True,
                                     blank=True,
                                     help_text='permanent address of student')

    madrasa       = models.ForeignKey(Madrasa, on_delete=models.CASCADE, related_name='students')
    markaz        = models.CharField(max_length=127,
                                     blank=True,
                                     help_text="If the student's madrasa is the markaz then leave it blank'"
                                               " otherwise enter the markaz name")
    marhala       = models.CharField(max_length=10,
                                     choices=MARHALA)

    reg_year      = models.CharField(max_length=4,
                                     choices=REGISTRATION_YEARS,
                                     default='2018')
    registrar     = models.ForeignKey('auth.User', default=1)
    registered_at = models.DateTimeField(auto_now_add=True)
    updated_at    = models.DateTimeField(auto_now=True)
    is_active    = models.BooleanField(default=True, help_text='Active by Default')

    objects       = StudentManager()


    def get_absolute_url(self):
        return reverse('student:student_detail', kwargs={'pk':self.pk})

    def get_subject_list(self):
        subject_list = SUBJECT_LIST[self.marhala]
        return subject_list

    def get_result(self):
        try:
            return self.result
        except:
            return None

    def __str__(self):
        return '{}, (id: {})'.format(self.name, self.id)

    def save(self, *args, **kwargs):
        if self.markaz:
            return super(Student, self).save(*args, **kwargs)

        if self.madrasa.is_markaz:
            self.markaz = self.madrasa.name
        return super(Student, self).save(*args, **kwargs)

    class Meta:
        ordering = ['-registered_at','-updated_at']

student/forms.py
from django import forms

from .models import Student


class StudentCreateForm(forms.ModelForm):
    # name = forms.CharField()
    class Meta:
        model = Student
        fields = ['name',
                  'father',
                  'address',
                  'madrasa',
                  'marhala',
                  'markaz',
                  'reg_year',
                  'is_active']
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),
            'father': forms.TextInput(attrs={'class': 'form-control'}),
            'address': forms.TextInput(attrs={'class': 'form-control'}),
            'madrasa': forms.Select(attrs={'class': 'form-control'}),
            'marhala': forms.Select(attrs={'class': 'form-control'}),
            'markaz': forms.TextInput(attrs={'class': 'form-control'}),
            'reg_year': forms.Select(attrs={'class': 'form-control'}),
            'is_active': forms.CheckboxInput(),
        }

student/views.py
from django.shortcuts import reverse
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import (CreateView,
                                  DetailView,
                                  UpdateView,
                                  ListView)
from .models import Student
from .forms import StudentCreateForm

class StudentDetail(DetailView):
    model = Student
    template_name = 'student/student_detail.html'


class StudentList(LoginRequiredMixin, ListView):
    model = Student
    template_name = 'student/student_list.html'


class StudentWithoutResultList(LoginRequiredMixin, ListView):
    template_name = 'student/student_list.html'
    def get_queryset(self):
        return Student.objects.without_result()


class StudentCreate(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    form_class = StudentCreateForm
    template_name = 'student/student_create_form.html'

    success_message = 'Student ID: %(id)s Successfully Created'
    def get_success_message(self, cleaned_data):
        return self.success_message % dict(
            cleaned_data,
            id=self.object.id,
        )

    def get_success_url(self):
        if 'add_another' in self.request.POST:
            return reverse('student:student_add')
        else:
            return reverse('student:student_detail', kwargs={'pk':self.object.id})



class StudentUpdate(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = Student
    form_class = StudentCreateForm
    template_name = 'student/student_update_form.html'

    success_message = 'Student ID: %(id)s Successfully Updated'
    def get_success_message(self, cleaned_data):
        return self.success_message % dict(
            cleaned_data,
            id=self.object.id,
        )

student/templates/student/student_create_form.html
{% extends 'base.html' %}

{% block content %}
    <div class="col-md-6 col-md-offset-3">
        <div class="form-group">
            <form action="" method="post">{% csrf_token %}
                {% for field in form %}
                    {% if not forloop.last %}
                        <div class="form-group">
                            {% if field.errors %}
                                {% for error in field.errors %}
                                    <span style="color: red"> {{ error }} </span><br/>
                                {% endfor %}
                            {% endif %}
                            <div class="input-group">
                                <span class="input-group-addon"><b>{{ field.label }}</b></span>
                                {{ field }}
                            </div>
                            <p class="help-block">{{ field.help_text }}</p>
                        </div>
                    {% endif %}
                {% endfor %}

                <div class="row col-md-4">
                    <div class="input-group">
                        <span class="input-group-addon"><b>{{ form.is_active.label }}</b></span>
                        <span class="input-group-addon">{{ form.is_active }}</span>
                    </div>
                    <p class="help-block">{{ form.is_active.help_text }}</p>
                </div>

                <br/><br/>
                <input type="submit" value="Save" class="btn btn-default pull-right"/>
                <input type="submit" name="add_another" value="Save and Add Another"
                       class="btn btn-default pull-right"/>
            </form>
        </div>
    </div>
{% endblock %}

student/templates/student/student_detail.html
{% extends 'base.html' %}

{% block content %}
    <div class="row">
        <div class="col-md-6 col-md-offset-3">
            <div>
                <strong>Reg ID: </strong>{{ student.id }}<br>
                <strong>Name: </strong>{{ student.name }}<br>
                <strong>Father: </strong>{{ student.father }}<br>
                <strong>Adress: </strong>{{ student.address }}<br>
                <strong>is Active: </strong>{% if student.is_active %}Yes{% else %}No{% endif %}
            </div>
            <br/>

            <div>
                <strong>Reg Year: </strong>{{ student.reg_year }}<br>
                <strong>Marhala: </strong>{{ student.marhala }}<br>
                <strong>Madrasa: </strong>{{ student.madrasa }}<br>
                <strong>Markaz: </strong>{{ student.markaz }}<br/>
            </div>
            <br/>

            {% if request.user.is_authenticated %}
                <div>
                    <strong>Registrar: </strong>{{ student.registrar }}<br>
                    <strong>Registered at: </strong>{{ student.registered_at }}<br>
                    <strong>Updated at: </strong>{{ student.updated_at }}<br>
                </div><br/>
            {% endif %}

            <hr/>
            {% if student.result %}
                <p><a href="{% url 'result:result_detail' id=student.id %}">View Result of this Student</a></p><br/>
            {% endif %}
            {% if request.user.is_authenticated %}
                <p><a href="{% url 'student:student_update' pk=student.id %}">Update Student Info.</a></p>
                <p><a href="{% url 'student:student_list' %}">All Students</a></p>
            {% endif %}
        </div>
    </div>
{% endblock %}

student/templates/student/student_list.html
{% extends 'base.html' %}

{% block content %}
    <div class="col-md-10 col-md-offset-1">
        <div class="table-responsive">
            <table class="table table-hover table-white">
                <thead>
                <tr>
                    <th scope="col">Reg. ID</th>
                    <th scope="col">Name</th>
                    <th scope="col">Father</th>
                    <th scope="col">Marhala</th>
                    <th scope="col">Madrasa</th>
                    <th scope="col">Reg Year</th>
                    <th scope="col">Registrar</th>
                    <th scope="col">Address</th>
                    <th scope="col">Is Active</th>
                </tr>
                </thead>

                <tbody>
                {% for student in student_list %}
                    <tr>
                        <th scope="row">{{ student.id }}</th>
                        <td><a href="{% url 'student:student_detail' pk=student.pk %}">
                            {{ student.name }}
                        </a></td>
                        <td>{{ student.father }}</td>
                        <td>{{ student.marhala }}</td>
                        <td>
                            <a href="{% url 'madrasa:madrasa_detail' pk=student.madrasa.pk %}">{{ student.madrasa }}</a>
                        </td>
                        <td>{{ student.reg_year }}</td>
                        <td>{{ student.registrar }}</td>
                        <td>{{ student.address }}</td>
                        <td>
                            {% if student.is_active %}
                                Yes
                            {% else %}
                                No
                            {% endif %}
                        </td>
                    </tr>
                {% empty %}
                    <p>No Student Registered yet.</p>
                {% endfor %}
            </table>
        </div>
    </div>

{% endblock %}

student/templates/student/student_update_form.html
{% extends 'base.html' %}

{% block content %}
    <div class="col-md-6 col-md-offset-3">
        <div class="form-group">
            <form action="" method="post">{% csrf_token %}
                {% for field in form %}
                    {% if not forloop.last %}
                        <div class="form-group">
                            {% if field.errors %}
                                {% for error in field.errors %}
                                    <span style="color: red"> {{ error }} </span><br/>
                                {% endfor %}
                            {% endif %}
                            <div class="input-group">
                                <span class="input-group-addon"><b>{{ field.label }}</b></span>
                                {{ field }}
                            </div>
                            <p class="help-block">{{ field.help_text }}</p>
                        </div>
                    {% endif %}
                {% endfor %}

                <div class="row col-md-4">
                    <div class="input-group">
                        <span class="input-group-addon"><b>{{ form.is_active.label }}</b></span>
                        <span class="input-group-addon">{{ form.is_active }}</span>
                    </div>
                    <p class="help-block">{{ form.is_active.help_text }}</p>
                </div>

                <br/><br/>
                <input type="submit" value="Save" class="btn btn-default pull-right"/>
            </form>
        </div>
    </div>
{% endblock %}