api/urls.py
from django.conf.urls import url, include
from django.views.generic import TemplateView


urlpatterns = [
    url(r'^result/', include('result.api.urls', namespace='result_api')),
]

befaq/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.views import login, logout
from django.views.generic import RedirectView

urlpatterns = [
    url(r'^login/$', login, {'template_name': 'login.html'}, name='login'),
    url(r'^logout/$', logout, {'next_page': '/'}, name='logout'),
    url(r'^admin/', admin.site.urls),

    url(r'^api/', include('api.urls')),
    url(r'^result/', include('result.urls')),
    url(r'^madrasa/', include('madrasa.urls')),
    url(r'^student/', include('student.urls')),

    url(r'^$', RedirectView.as_view(url='/result', permanent=False))
]

madrasa/urls.py
from django.conf.urls import url

from .views import (MadrasaCreate,
                    MadrasaDetail,
                    MadrasaUpdate,
                    MadrasaList, )

app_name = 'madrasa'

urlpatterns = [
    url(r'add', MadrasaCreate.as_view(), name='madrasa_add'),
    url(r'update/(?P<pk>\d+)/', MadrasaUpdate.as_view(), name='madrasa_update'),
    url(r'list', MadrasaList.as_view(), name='madrasa_list'),
    url(r'(?P<pk>\d+)/', MadrasaDetail.as_view(), name='madrasa_detail'),
]

result/api/urls.py
from django.conf.urls import url

from result.api.views import (ResultDetailAPIView,
                              TopStudentResultsAPIView,
                              api_home)

urlpatterns = [
    url(r'^(?P<id>\d+)/$', ResultDetailAPIView.as_view(), name='result_detail'),
    url(r'^top/$', TopStudentResultsAPIView.as_view(), name='top_results'),
    url(r'^$', api_home, name='api_home'),

]

result/urls.py
from django.conf.urls import url

from result.views import (result_search,
                          result_detail,
                          top_results,
                          add_result,
                          select_student_to_add_result,
                          )


app_name = 'result'

urlpatterns = [
    url(r'^top/$', top_results, name='top_results'),

    url(r'^add/$', select_student_to_add_result, name='select_student_to_add_result'),
    url(r'^add/(?P<id>\d+)/$', add_result, name='add_result'),

    url(r'^(?P<id>\d+)/$', result_detail, name='result_detail'),
    url(r'^$', result_search, name='result_search'),
]

student/urls.py
from django.conf.urls import url

from .views import (StudentCreate,
                    StudentDetail,
                    StudentUpdate,
                    StudentList,
                    StudentWithoutResultList,)

app_name = 'student'

urlpatterns = [
    url(r'^add$', StudentCreate.as_view(), name='student_add'),
    url(r'^update/(?P<pk>\d+)/$', StudentUpdate.as_view(), name='student_update'),
    url(r'^list$', StudentList.as_view(), name='student_list'),
    url(r'^without_result$', StudentWithoutResultList.as_view(), name='student_without_result'),
    url(r'^(?P<pk>\d+)/$', StudentDetail.as_view(), name='student_detail'),
]

result/models.py
from django.db import models
from django.core.urlresolvers import reverse
from django.core.validators import MaxValueValidator, MinValueValidator

from student.models import Student
from .utils import grade_calculator

# GRADE_LIST = (
#     ('mumtaz', 'Mumtaz'),
#     ('jaiyed_jiddan', 'Jaiyed Jiddan'),
#     ('jaiyed', 'Jaiyed'),
#     ('makbul', 'Makbul'),
#     ('rasib', 'Rasib'),
# )

class Result(models.Model):
    student    = models.OneToOneField(Student, on_delete=models.CASCADE)

    subject_1  = models.IntegerField(default=0,validators=[MinValueValidator(0),MaxValueValidator(100)])
    subject_2  = models.IntegerField(default=0,validators=[MinValueValidator(0),MaxValueValidator(100)])
    subject_3  = models.IntegerField(default=0,validators=[MinValueValidator(0),MaxValueValidator(100)])
    subject_4  = models.IntegerField(default=0,validators=[MinValueValidator(0),MaxValueValidator(100)])
    subject_5  = models.IntegerField(default=0,validators=[MinValueValidator(0),MaxValueValidator(100)])
    subject_6  = models.IntegerField(default=0,validators=[MinValueValidator(0),MaxValueValidator(100)])
    subject_7  = models.IntegerField(default=0,validators=[MinValueValidator(0),MaxValueValidator(100)])
    subject_8  = models.IntegerField(default=0,validators=[MinValueValidator(0),MaxValueValidator(100)])
    subject_9  = models.IntegerField(default=0,validators=[MinValueValidator(0),MaxValueValidator(100)])
    subject_10 = models.IntegerField(default=0,validators=[MinValueValidator(0),MaxValueValidator(100)])

    total_num   = models.IntegerField(default=0)
    average_num = models.FloatField(default=0)
    grade       = models.CharField(max_length=20, default='', blank=True)

    def __str__(self):
        return 'result of {} ({})'.format(self.student.name, self.student.id)

    def save(self, *args, **kwargs):
        # calculate total number and average number
        # and add them to self.total_num & self.average_num
        student_subject_list = self.student.get_subject_list()

        # adding total number
        total_num = 0
        for i, subject in enumerate(student_subject_list, 1):
            total_num += getattr(self, 'subject_{}'.format(i), 0)
        self.total_num = total_num

        # adding average number
        try:
            self.average_num = round(total_num/ len(student_subject_list), 2)
        except:
            self.average_num = 0

        # calculate student's Grade and
        # add to self.grade
        grade = grade_calculator(self)
        self.grade = grade

        return super(Result, self).save(*args, **kwargs)

    # def get_absolute_url(self):
    #     return reverse('website:student_detail', kwargs={'reg_id':self.student.reg_id,
    #                                                        'reg_year':self.student.reg_year})

result/forms.py
from django import forms
from django.core.validators import MinValueValidator, MaxValueValidator


class SearchResultForm(forms.Form):
    id = forms.IntegerField(label="Student's ID",
                            required=True,
                            validators=[MinValueValidator(1)],
                            widget=forms.TextInput(attrs={'class': 'form-control'}))


class AddResultForm(forms.Form):
    def __init__(self, *args, **kwargs):
        subject_list = kwargs.pop('subject_list')
        super(AddResultForm, self).__init__(*args, **kwargs)

        for i, subject in enumerate(subject_list, 1):
            self.fields['subject_{}'.format(i)] = forms.IntegerField(label=subject,
                                                                     required=True,
                                                                     validators=[MinValueValidator(0),
                                                                                 MaxValueValidator(100)],
                                                                     widget=forms.TextInput(
                                                                         attrs={'class': 'form-control',
                                                                                }))

    def get_results(self):
        results = {}
        for name, value in self.cleaned_data.items():
            if name.startswith('subject_'):
                results[name] = value
        return results


class ResultFilterForm(forms.Form):
    REGISTRATION_YEARS = (
        ('2016', '2016'),
        ('2017', '2017'),
        ('2018', '2018'),
    )
    MARHALA = [
        ('', 'All Marhala'),
        ('takmil', 'Takmil'),
        ('fazilat', 'Fazilat'),
        ('sanabia', 'Sanabia Ulia'),
        ('mutawassitah', 'Mutawassitah'),
        ('ibtedaiyah', 'Ibtedaiyah'),
        ('hifz', 'Hifzul Quran'),
        ('tazbid', 'Ilmut Tazbid wal Qirat'),
    ]

    madrasa = forms.CharField(required=False,
                              label='Madrasa',
                              widget=forms.TextInput(attrs={'class': 'form-control',
                                                            'placeholder': 'Name or ID'}))

    marhala = forms.ChoiceField(choices=MARHALA,
                                label='Marhala',
                                required=False,
                                widget=forms.Select(attrs={'class': 'form-control'}))

    reg_year = forms.ChoiceField(choices=REGISTRATION_YEARS,
                                 label='Reg Year',
                                 initial='2018',
                                 required=False,
                                 widget=forms.Select(attrs={'class': 'form-control'}))

result/api/views.py
from rest_framework.decorators import api_view
from rest_framework.response import Response
from rest_framework.status import HTTP_406_NOT_ACCEPTABLE
from rest_framework.generics import RetrieveAPIView, ListAPIView

from result.api.serializers import StudentResultSerializer, TopStudentResultsSerializer
from student.models import Student


@api_view(['get'])
def api_home(self):
    content = {'single_result':'To retrieve single result Go to www.befaq.ml/api/result/<id>/ where <id> is student registration ID',
               'result_list':'To retrieve top result list Go to www.befaq.ml/api/result/top/',
               'detail':'Learn Detail on www.befaq.ml/api/'}
    return Response(content, HTTP_406_NOT_ACCEPTABLE)


class ResultDetailAPIView(RetrieveAPIView):
    serializer_class = StudentResultSerializer
    queryset = Student.objects.all()
    lookup_field = 'id'

class TopStudentResultsAPIView(ListAPIView):
    serializer_class = TopStudentResultsSerializer

    def get_queryset(self):
        # retrieve all student object with result
        queryset = Student.objects.with_result()

        # filter student objects with get parameters if given.
        # first filter them with reg_year, default 2018
        reg_year = self.request.GET.get('reg_year', 2018)
        queryset = queryset.filter(reg_year=int(reg_year))

        # filter them with marhala if given
        marhala = self.request.GET.get('marhala')
        if marhala:
            queryset = queryset.filter(marhala__icontains=marhala)

        # filter them with madrasa if givem
        madrasa = self.request.GET.get('madrasa')
        if madrasa:
            try: # try to find if the given 'madrasa' parameter is int type (for madrasa ID)
                madrasa = int(madrasa) # convert madrasa id to integer type
                queryset = queryset.filter(madrasa__id=madrasa)
            except: # if madrasa not an int, then think of his as string (madrasa name)
                queryset = queryset.filter(madrasa__name=madrasa)

        return queryset

result/views.py
from collections import OrderedDict

from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.http import Http404
from django.shortcuts import render, reverse, redirect, get_object_or_404

from student.models import Student
from madrasa.models import Madrasa
from .models import Result
from .forms import SearchResultForm, ResultFilterForm, AddResultForm


def result_search(request):
    total_madrasa = Madrasa.objects.all().count()
    total_student = Student.objects.all().count()

    if request.method == 'POST':
        form = SearchResultForm(request.POST)
        if form.is_valid():
            id = form.cleaned_data.get('id')
            return redirect(reverse('result:result_detail', kwargs={'id': id}))

    else:
        form = SearchResultForm()

    context = {
        'form': form,
        'total_madrasa': total_madrasa,
        'total_student': total_student,
    }
    return render(request, 'result/result_search.html', context)


@login_required
def select_student_to_add_result(request):
    context = {}  # initialize context
    if request.method == 'POST':
        form = SearchResultForm(request.POST)
        if form.is_valid():
            id = form.cleaned_data.get('id')
            context['student_id'] = id
            # checking if the student of given id already exists or not
            student = Student.objects.filter(id=id)
            if student.exists():
                # checking if the student's result already exists or not
                result_exists = Result.objects.filter(student__id=id).exists()
                if result_exists:
                    # if result already exists then send this information as error
                    context['result_exists'] = True
                # if student of given id is exists and his result not exists
                # then go to add result page for adding new result for this student
                else:
                    return redirect(reverse('result:add_result', kwargs={'id': id}))
            else:  # if student not exists then send this information
                context['student_not_exists'] = True
    else:
        form = SearchResultForm()

    context['form'] = form
    return render(request, 'result/select_student_to_add_result.html', context)


@login_required
def add_result(request, id):
    student = get_object_or_404(Student, id=id)
    # if this student already have result then raise 404 error
    result_exists = Result.objects.filter(student__id=id).exists()
    if result_exists:
        raise Http404

    subject_list = student.get_subject_list()

    add_result_form = AddResultForm(request.POST or None, subject_list=subject_list)
    if add_result_form.is_valid():
        subject_result_dict = add_result_form.get_results()
        # if all results is valid then create new result object
        # and add current student to this result.
        Result.objects.create(student=student, **subject_result_dict)
        messages.success(request, 'Result for Student ID: {} Successfully Added'.format(student.id))
        # after successfully create result, return to student's result page
        # or to new result add page, if submitted 'save and add new result' button
        if 'add_another' in request.POST:
            return redirect('result:select_student_to_add_result')
        return redirect(reverse('result:result_detail', kwargs={'id': student.id}))

    context = {'add_result_form': add_result_form,
               'student': student,
               }
    return render(request, 'result/add_result.html', context)


def result_detail(request, id=None):
    result = get_object_or_404(Result, student__id=id)
    student = result.student

    result_dict = OrderedDict()
    for i, subject in enumerate(student.get_subject_list(), 1):
        result_dict[subject] = getattr(result, 'subject_{}'.format(i), 0)

    context = {
        'student': student,
        'result': result_dict,
    }
    return render(request, 'result/result_detail.html', context)


def top_results(request):
    results = Result.objects.all().order_by('-average_num', '-total_num')

    # try to find marhala and madrasa on get method
    # then filter results based on madrasa or marhala
    filter_info = []  # show filter information as message on top results page
    marhala = request.GET.get('marhala')
    if request.GET.get('marhala'):
        results = results.filter(student__marhala__icontains=marhala)
        filter_info.append('Marhala: {}'.format(marhala))  # include marhala into filter info

    madrasa = request.GET.get('madrasa')
    if request.GET.get('madrasa'):
        try:
            madrasa_id = int(madrasa)
            results = results.filter(student__madrasa__id=madrasa_id)
            filter_info.append('Madrasa ID: {}'.format(madrasa_id))  # include madrasa id into filter info
        except:
            results = results.filter(student__madrasa__name__icontains=madrasa)
            filter_info.append('Madrasa: {}'.format(madrasa))  # include madrasa name into filter info

    reg_year = request.GET.get('reg_year', 2018)
    results = results.filter(student__reg_year=int(reg_year))
    filter_info.append('Year: {}'.format(reg_year))  # include registration Year into filter info

    # convert filter_info list to comma separated String
    filter_info = ', '.join(filter_info)

    result_filter_form = ResultFilterForm(request.GET or None)
    context = {
        'result_filter_form': result_filter_form,
        'filter_info': filter_info,
        'results': results[:40],  # always return top 40 results
    }
    return render(request, 'result/top_results.html', context)

result/templates/result/add_result.html
{% extends 'base.html' %}

{% block content %}
    <div class="row">
        <div class="col-md-5 col-md-offset-2">
            <strong>Reg ID: </strong>{{ student.id }}<br>
            <strong>Name: </strong>{{ student.name }}<br>
            <strong>Father: </strong>{{ student.father }}<br>
            <strong>Adress: </strong>{{ student.address }}<br>
            {% if not student.is_active %}<strong><i>Deactivated</i></strong>{% endif %}
        </div>
        <div class="col-md-5">
            <strong>Reg Year: </strong>{{ student.reg_year }}<br>
            <strong>Marhala: </strong>{{ student.marhala }}<br>
            <strong>Madrasa: </strong><a
                href="{% url 'madrasa:madrasa_detail' pk=student.madrasa.pk %}">{{ student.madrasa }}</a> <br>
            <strong>Markaz: </strong>{{ student.markaz }}<br>
        </div>
        <br/>
        <hr/>

        <div class="col-md-6 col-md-offset-3">
            <h3>Add Result</h3>
            <form method="post" action="">{% csrf_token %}
                {% for field in add_result_form %}
                    <div class="form-group">
                        {% if field.errors %}
                            {% for error in field.errors %}
                                <span style="color: red"> {{ error }} </span><br/>
                            {% endfor %}
                        {% endif %}
                        <div class="input-group">
                            <span class="input-group-addon"><b>{{ field.label }}</b></span>
                            {{ field }}
                        </div>
                        <p class="help-block">{{ field.help_text }}</p>
                    </div>
                {% endfor %}

                <input type="submit" value="Save" class="btn btn-default pull-right"/>
                <input type="submit" name="add_another" value="Save and Add Another"
                       class="btn btn-default pull-right"/>
                <br/>
                <br/>
                <br/>
            </form>
        </div>
    </div>
{% endblock %}

result/templates/result/result_detail.html
{% extends 'base.html' %}

{% block content %}
    <div class="row">
        <div class="col-md-5 col-md-offset-2">
            <strong>Reg ID: </strong>{{ student.id }}<br>
            <strong>Name: </strong><a href="{% url 'student:student_detail' pk=student.pk %}">{{ student.name }}</a> <br>
            <strong>Father: </strong>{{ student.father }}<br>
            <strong>Adress: </strong>{{ student.address }}<br>
            {% if not student.is_active %}<strong><i>Deactivated</i></strong>{% endif %}
        </div>
        <div class="col-md-5">
            <strong>Reg Year: </strong>{{ student.reg_year }}<br>
            <strong>Marhala: </strong>{{ student.marhala }}<br>
            <strong>Madrasa: </strong><a href="{% url 'madrasa:madrasa_detail' pk=student.madrasa.pk %}">{{ student.madrasa }}</a> <br>
            <strong>Markaz: </strong>{{ student.markaz }}<br>
        </div>
        <br/>

        <div class="col-md-8 col-md-offset-2">
        <hr />
            <h3>Result</h3>
            <div class="table-responsive">
                <table class="table table-hover table-white">
                    <thead>
                    <tr>
                        <th scope="col">Subject</th>
                        <th scope="col">Number</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for subject, number in result.items %}
                        <tr>
                            <td>{{ subject }}</td>
                            <td>{{ number }}</td>
                        </tr>
                    {% endfor %}
                    <tr>
                        <th>Total Number</th>
                        <td><strong>{{ student.result.total_num }}</strong></td>
                    </tr>
                    <tr>
                        <th>Average Number</th>
                        <td><strong>{{ student.result.average_num }}</strong></td>
                    </tr>
                    <tr>
                        <th>Grade</th>
                        <td><strong>{{ student.result.grade }}</strong></td>
                    </tr>

                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock %}

result/templates/result/result_search.html
{% extends 'base.html' %}

{% block content %}
    <div class="col-md-8 col-md-offset-2">
        <div class="form-group">
            <form action="" method="post" class="form-inline">{% csrf_token %}
                {{ form.as_table }}
                <input type="submit" value="search" class="btn btn-default"/>
            </form>
        </div>
        <br/>
        <hr/>
        <h4>Total Registered Students: {{ total_student }}</h4>
        <h4>Total Registered Madrasa: {{ total_madrasa }}</h4>
    </div>
{% endblock %}

result/templates/result/select_student_to_add_result.html
{% extends 'base.html' %}

{% block content %}
    <div class="col-md-8 col-md-offset-2">
    <h4>Enter student ID to set result...</h4>
        <div class="form-group">
            <form action="" method="post" class="form-inline">{% csrf_token %}
                {{ form.as_table }}
                <input type="submit" value="add result" class="btn btn-default"/>
            </form>
        </div>
        {% if result_exists %}
            <div>
                <p class="bg-warning">Result of Student ID: {{ student_id }} already exists.
                <a href="{% url 'result:result_detail' id=student_id %}">View Result</a></p>
            </div>
        {% endif %}

        {% if student_not_exists %}
            <div>
                <p class="bg-danger">Student ID: <b>{{ student_id }}</b> Not Exists.<br/></p>
            </div>
        {% endif %}
    </div>
{% endblock %}

result/templates/result/top_results.html
{% extends 'base.html' %}

{% block content %}
    <div class="row">
        <div class="col-md-10 col-md-offset-1">
            <div class="form-group">
                <form action="{% url 'result:top_results' %}" method="get" class="form-inline">
                    {{ result_filter_form.as_table }}
                    <input type="submit" value="filter" class="btn btn-info">
                </form>
                <br/><br/>
                {% if filter_info %}
                    <p class="bg-info">Top Results of: {{ filter_info }}</p>
                {% endif %}
                <hr/>
            </div>
        </div>


        <div class="col-md-10 col-md-offset-1">
            <div class="table-responsive">
                <table class="table table-hover table-white">
                    <thead>
                    <tr>
                        <th scope="col">SN</th>
                        <th scope="col">Reg. ID</th>
                        <th scope="col">Reg. Year</th>
                        <th scope="col">Name</th>
                        <th scope="col">Madrasa</th>
                        <th scope="col">Marhala</th>
                        <th scope="col">Average num</th>
                        <th scope="col">Grade</th>
                        <th scope="col">full Result</th>

                    </tr>
                    </thead>
                    <tbody>
                    {% for result in results %}
                        <tr>
                            <th scope="row">{{ forloop.counter }})</th>
                            <td>{{ result.student.id }}</td>
                            <td>{{ result.student.reg_year }}</td>
                            <td><a href="{% url 'student:student_detail' pk=result.student.pk %}">
                                {{ result.student.name }}</a>
                            </td>
                            <td>
                                <a href="{% url 'madrasa:madrasa_detail' pk=result.student.madrasa.pk %}">{{ result.student.madrasa }}</a>
                            </td>
                            <td>{{ result.student.marhala }}</td>
                            <td>{{ result.average_num }}</td>
                            <td>{{ result.grade }}</td>
                            <td><a href="{% url 'result:result_detail' id=result.student.id %}">Result</a>
                            </td>


                        </tr>

                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock %}