api/urls.py
from django.conf.urls import url, include
from django.views.generic import TemplateView


urlpatterns = [
    url(r'^result/', include('result.api.urls', namespace='result_api')),
]

befaq/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.views import login, logout
from django.views.generic import RedirectView

urlpatterns = [
    url(r'^login/$', login, {'template_name': 'login.html'}, name='login'),
    url(r'^logout/$', logout, {'next_page': '/'}, name='logout'),
    url(r'^admin/', admin.site.urls),

    url(r'^api/', include('api.urls')),
    url(r'^result/', include('result.urls')),
    url(r'^madrasa/', include('madrasa.urls')),
    url(r'^student/', include('student.urls')),

    url(r'^$', RedirectView.as_view(url='/result', permanent=False))
]

madrasa/urls.py
from django.conf.urls import url

from .views import (MadrasaCreate,
                    MadrasaDetail,
                    MadrasaUpdate,
                    MadrasaList, )

app_name = 'madrasa'

urlpatterns = [
    url(r'add', MadrasaCreate.as_view(), name='madrasa_add'),
    url(r'update/(?P<pk>\d+)/', MadrasaUpdate.as_view(), name='madrasa_update'),
    url(r'list', MadrasaList.as_view(), name='madrasa_list'),
    url(r'(?P<pk>\d+)/', MadrasaDetail.as_view(), name='madrasa_detail'),
]

result/urls.py
from django.conf.urls import url

from result.views import (result_search,
                          result_detail,
                          top_results,
                          add_result,
                          select_student_to_add_result,
                          )


app_name = 'result'

urlpatterns = [
    url(r'^top/$', top_results, name='top_results'),

    url(r'^add/$', select_student_to_add_result, name='select_student_to_add_result'),
    url(r'^add/(?P<id>\d+)/$', add_result, name='add_result'),

    url(r'^(?P<id>\d+)/$', result_detail, name='result_detail'),
    url(r'^$', result_search, name='result_search'),
]

student/urls.py
from django.conf.urls import url

from .views import (StudentCreate,
                    StudentDetail,
                    StudentUpdate,
                    StudentList,
                    StudentWithoutResultList,)

app_name = 'student'

urlpatterns = [
    url(r'^add$', StudentCreate.as_view(), name='student_add'),
    url(r'^update/(?P<pk>\d+)/$', StudentUpdate.as_view(), name='student_update'),
    url(r'^list$', StudentList.as_view(), name='student_list'),
    url(r'^without_result$', StudentWithoutResultList.as_view(), name='student_without_result'),
    url(r'^(?P<pk>\d+)/$', StudentDetail.as_view(), name='student_detail'),
]

templates/snippets/messages.html
{% for message in messages %}
  <div class="alert {{ message.tags }} alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    {{ message }}
  </div>
{% endfor %}

templates/snippets/navbar.html
<nav class="navbar navbar-default">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar"
                    aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/">Befaq Result</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li><a href="{% url 'result:result_search' %}">Search Result</a></li>
                <li><a href="{% url 'result:top_results' %}">Top Results</a></li>

                {% if request.user.is_authenticated %}
                    <li><a href="{% url 'logout' %}?next={{ request.path|urlencode }}">Logout</a></li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                           aria-expanded="false">Register<span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><a href="{% url 'student:student_add' %}">Add Student</a></li>
                            <li><a href="{% url 'result:select_student_to_add_result' %}">Add Result</a></li>
                            <li><a href="{% url 'madrasa:madrasa_add' %}">Add Madrasa</a></li>
{#                            <li role="separator" class="divider"></li>#}
{#                            <li class="dropdown-header">Update</li>#}
{#                            <li><a href="#">Update Student</a></li>#}
{#                            <li><a href="#">Update Madrasa</a></li>#}
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                           aria-expanded="false">List<span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><a href=" {% url 'student:student_list' %}">All Students</a></li>
                            <li><a href=" {% url 'student:student_without_result' %}">Students Without Results</a></li>
                            <li role="separator" class="divider"></li>
                            <li><a href="{% url 'madrasa:madrasa_list' %}">All Madrasa</a></li>
                        </ul>
                    </li>
                {% else %}
                    <li><a href="{% url 'login' %}?next={{ request.path|urlencode }}">Login</a></li>
                {% endif %}
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <li><a href="/">Home</a></li>
                <li><a href="/about">About</a></li>
                <li><a href="/contact">Contact</a></li>
                <li><a href="/api">API</a>
            </ul>
        </div><!--/.nav-collapse -->
    </div><!--/.container-fluid -->
</nav>