api/urls.py
from django.conf.urls import url, include
from django.views.generic import TemplateView


urlpatterns = [
    url(r'^result/', include('result.api.urls', namespace='result_api')),
]

befaq/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.views import login, logout
from django.views.generic import RedirectView

urlpatterns = [
    url(r'^login/$', login, {'template_name': 'login.html'}, name='login'),
    url(r'^logout/$', logout, {'next_page': '/'}, name='logout'),
    url(r'^admin/', admin.site.urls),

    url(r'^api/', include('api.urls')),
    url(r'^result/', include('result.urls')),
    url(r'^madrasa/', include('madrasa.urls')),
    url(r'^student/', include('student.urls')),

    url(r'^$', RedirectView.as_view(url='/result', permanent=False))
]

madrasa/urls.py
from django.conf.urls import url

from .views import (MadrasaCreate,
                    MadrasaDetail,
                    MadrasaUpdate,
                    MadrasaList, )

app_name = 'madrasa'

urlpatterns = [
    url(r'add', MadrasaCreate.as_view(), name='madrasa_add'),
    url(r'update/(?P<pk>\d+)/', MadrasaUpdate.as_view(), name='madrasa_update'),
    url(r'list', MadrasaList.as_view(), name='madrasa_list'),
    url(r'(?P<pk>\d+)/', MadrasaDetail.as_view(), name='madrasa_detail'),
]

madrasa/models.py
from django.db import models
from django.shortcuts import reverse

class Madrasa(models.Model):
    name      = models.CharField(max_length=127, unique=True)
    address   = models.CharField(max_length=255, blank=True)
    is_markaz = models.BooleanField(default=False)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('madrasa:madrasa_detail', kwargs={'pk':self.pk})

madrasa/forms.py
from django import forms


class MadrasaCreateUpdateForm(forms.Form):
    id = forms.IntegerField()
    name = forms.CharField()
    address = forms.CharField()
    is_markaz = forms.BooleanField()

madrasa/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.views.generic import (CreateView,
                                  DetailView,
                                  UpdateView,
                                  ListView)

from .models import Madrasa


class MadrasaDetail(DetailView):
    model = Madrasa
    template_name = 'madrasa/madrasa_detail.html'

class MadrasaList(LoginRequiredMixin, ListView):
    model = Madrasa
    template_name = 'madrasa/madrasa_list.html'

class MadrasaCreate(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    model = Madrasa
    fields = ['name','address','is_markaz']
    template_name = 'madrasa/madrasa_create_form.html'

    success_message = 'Madrasa ID: %(id)s Successfully Created'
    def get_success_message(self, cleaned_data):
        return self.success_message % dict(
            cleaned_data,
            id=self.object.id,
        )

class MadrasaUpdate(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = Madrasa
    fields = ['name','address','is_markaz']
    template_name = 'madrasa/madrasa_create_form.html'

    success_message = 'Madrasa ID: %(id)s Successfully Updated'
    def get_success_message(self, cleaned_data):
        return self.success_message % dict(
            cleaned_data,
            id=self.object.id,
        )

madrasa/templates/madrasa/madrasa_create_form.html
{% extends 'base.html' %}

{% block content %}
    <div class="col-md-8 col-md-offset-2">
        <div class="form-group">
            <form action="" method="post">{% csrf_token %}
                {{ form.as_p }}

                <input type="submit" class="btn btn-default" />
            </form>
        </div>
    </div>
{% endblock %}

madrasa/templates/madrasa/madrasa_detail.html
{% extends 'base.html' %}

{% block content %}
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <strong>Registration ID: </strong>{{ madrasa.id }}<br/>
            <strong>Name: </strong>{{ madrasa.name }}<br/>
            <strong>address: </strong>{{ madrasa.address }}<br/>
            This madrasa is <strong>{% if not  madrasa.is_markaz %}Not {% endif %}Markaz</strong>.

            <br/>
            <hr/>

            {% if request.user.is_authenticated %}
                <p><a href="{% url 'madrasa:madrasa_update' pk=madrasa.pk %}">Update Madrasa Info.</a>
                <p><a href="{% url 'madrasa:madrasa_list' %}">All Madrasa</a></p>
            {% endif %}
        </div>
    </div>
{% endblock %}

madrasa/templates/madrasa/madrasa_list.html
{% extends 'base.html' %}

{% block content %}
    <div class="col-md-10 col-md-offset-1">
        <div class="table-responsive">
            <table class="table table-hover table-white">
                <thead>
                <tr>
                    <th scope="col">Reg. ID</th>
                    <th scope="col">Name</th>
                    <th scope="col">Address</th>
                    <th scope="col">is Marhala</th>
                </tr>
                </thead>
                <tbody>
                {% for madrasa in madrasa_list %}
                    <tr>
                        <th scope="row">{{ madrasa.id }}</th>
                        <td><a href="{% url 'madrasa:madrasa_detail' pk=madrasa.pk %}">
                            {{ madrasa.name }}
                        </a></td>
                        <td>{{ madrasa.address }}</td>
                        <td>
                            {% if madrasa.is_markaz %}
                                Yes
                            {% else %}
                                No
                            {% endif %}
                        </td>
                    </tr>
                {% empty %}
                    <p>No Madrasa Registered yet.</p>
                {% endfor %}
            </table>
        </div>
    </div>

{% endblock %}